# Generated by Django 3.2.14 on 2023-11-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_id'),
        ('rate', '0002_auto_20231110_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie'),
        ),
    ]
