# Generated by Django 3.2.14 on 2023-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20231108_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
