# Generated by Django 3.2.14 on 2023-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tconst',
            field=models.CharField(max_length=9),
        ),
    ]
