# Generated by Django 3.2.14 on 2023-11-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_tconst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tconst',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
